/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

/**
 *
 * @author Cleiton
 */
public class GuiGerenciar_Análise_de_Crédito extends javax.swing.JFrame {

    /**
     * Creates new form GuiConsulta_Análise_de_Crédito
     */
    public GuiGerenciar_Análise_de_Crédito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo_Pesquisa = new javax.swing.ButtonGroup();
        Painel_Gerenciar_Analise_de_Credito = new javax.swing.JPanel();
        Painel_Analise_de_Credito = new javax.swing.JPanel();
        Painel_Pesquisa = new javax.swing.JPanel();
        lblPesquisa = new javax.swing.JLabel();
        rbtnCodigo_do_Cliente = new javax.swing.JRadioButton();
        rbtnNumero_da_Compra = new javax.swing.JRadioButton();
        rbtnTodos = new javax.swing.JRadioButton();
        txtCodigo_Cliente = new javax.swing.JTextField();
        txtNumero_Compra = new javax.swing.JTextField();
        Painel_Complemento_da_Pesquisa = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        cbxFiltro = new javax.swing.JComboBox<>();
        Painel_Período_da_Pesquisa = new javax.swing.JPanel();
        lblData_Inicial = new javax.swing.JLabel();
        lblData_Final = new javax.swing.JLabel();
        ftxtData_Inicial = new javax.swing.JFormattedTextField();
        ftxtData_Final = new javax.swing.JFormattedTextField();
        btnVoltar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAprovar = new javax.swing.JButton();
        btnReprovar = new javax.swing.JButton();
        Painel_Pedido = new javax.swing.JPanel();
        Pedido = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Análise de Crédito");
        setResizable(false);

        Painel_Pesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        lblPesquisa.setText("Pesquisar por:");

        Grupo_Pesquisa.add(rbtnCodigo_do_Cliente);
        rbtnCodigo_do_Cliente.setSelected(true);
        rbtnCodigo_do_Cliente.setText("Codigo do Cliente");

        Grupo_Pesquisa.add(rbtnNumero_da_Compra);
        rbtnNumero_da_Compra.setText("N° da Compra");

        Grupo_Pesquisa.add(rbtnTodos);
        rbtnTodos.setText("Todos");

        txtNumero_Compra.setEnabled(false);

        javax.swing.GroupLayout Painel_PesquisaLayout = new javax.swing.GroupLayout(Painel_Pesquisa);
        Painel_Pesquisa.setLayout(Painel_PesquisaLayout);
        Painel_PesquisaLayout.setHorizontalGroup(
            Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                        .addComponent(rbtnTodos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                        .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPesquisa)
                            .addComponent(rbtnCodigo_do_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnNumero_da_Compra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo_Cliente)
                            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                                .addComponent(txtNumero_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 158, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        Painel_PesquisaLayout.setVerticalGroup(
            Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                .addComponent(lblPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnCodigo_do_Cliente)
                    .addComponent(txtCodigo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnNumero_da_Compra)
                    .addComponent(txtNumero_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addComponent(rbtnTodos))
        );

        Painel_Complemento_da_Pesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Complemento da Pesquisa"));

        lblFiltro.setText("Filtrar por:");

        cbxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Aprovado", "Reprovado", "Pendente", "Em Transito", "Entregue" }));

        javax.swing.GroupLayout Painel_Complemento_da_PesquisaLayout = new javax.swing.GroupLayout(Painel_Complemento_da_Pesquisa);
        Painel_Complemento_da_Pesquisa.setLayout(Painel_Complemento_da_PesquisaLayout);
        Painel_Complemento_da_PesquisaLayout.setHorizontalGroup(
            Painel_Complemento_da_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Complemento_da_PesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Complemento_da_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFiltro)
                    .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        Painel_Complemento_da_PesquisaLayout.setVerticalGroup(
            Painel_Complemento_da_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Complemento_da_PesquisaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Painel_Período_da_Pesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Período da Pesquisa"));

        lblData_Inicial.setText("Data Inicial");

        lblData_Final.setText("Data Final");

        try {
            ftxtData_Inicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtData_Final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout Painel_Período_da_PesquisaLayout = new javax.swing.GroupLayout(Painel_Período_da_Pesquisa);
        Painel_Período_da_Pesquisa.setLayout(Painel_Período_da_PesquisaLayout);
        Painel_Período_da_PesquisaLayout.setHorizontalGroup(
            Painel_Período_da_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Período_da_PesquisaLayout.createSequentialGroup()
                .addGroup(Painel_Período_da_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData_Inicial)
                    .addComponent(ftxtData_Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Painel_Período_da_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftxtData_Final, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData_Final))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_Período_da_PesquisaLayout.setVerticalGroup(
            Painel_Período_da_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Período_da_PesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Período_da_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData_Inicial)
                    .addComponent(lblData_Final))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Período_da_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtData_Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtData_Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVoltar.setText("Voltar");

        btnBuscar.setText("Buscar");

        btnAprovar.setText("Aprovar");
        btnAprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprovarActionPerformed(evt);
            }
        });

        btnReprovar.setText("Reprovar");

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Pedido", "Valor Total", "Cliente", "Vendedor Responsável", "Situação"
            }
        ));
        Pedido.setViewportView(tblPedido);

        javax.swing.GroupLayout Painel_PedidoLayout = new javax.swing.GroupLayout(Painel_Pedido);
        Painel_Pedido.setLayout(Painel_PedidoLayout);
        Painel_PedidoLayout.setHorizontalGroup(
            Painel_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PedidoLayout.createSequentialGroup()
                .addComponent(Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Painel_PedidoLayout.setVerticalGroup(
            Painel_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_PedidoLayout.createSequentialGroup()
                .addComponent(Pedido, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Painel_Analise_de_CreditoLayout = new javax.swing.GroupLayout(Painel_Analise_de_Credito);
        Painel_Analise_de_Credito.setLayout(Painel_Analise_de_CreditoLayout);
        Painel_Analise_de_CreditoLayout.setHorizontalGroup(
            Painel_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Analise_de_CreditoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(Painel_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Analise_de_CreditoLayout.createSequentialGroup()
                        .addGroup(Painel_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Painel_Analise_de_CreditoLayout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addComponent(Painel_Complemento_da_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Painel_Período_da_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Painel_Pesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Painel_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Analise_de_CreditoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAprovar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReprovar)
                        .addGap(99, 99, 99))
                    .addGroup(Painel_Analise_de_CreditoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Painel_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        Painel_Analise_de_CreditoLayout.setVerticalGroup(
            Painel_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Analise_de_CreditoLayout.createSequentialGroup()
                .addGroup(Painel_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Analise_de_CreditoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Painel_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Painel_Complemento_da_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Painel_Período_da_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Painel_Analise_de_CreditoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Painel_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnBuscar)
                    .addComponent(btnAprovar)
                    .addComponent(btnReprovar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Painel_Gerenciar_Analise_de_CreditoLayout = new javax.swing.GroupLayout(Painel_Gerenciar_Analise_de_Credito);
        Painel_Gerenciar_Analise_de_Credito.setLayout(Painel_Gerenciar_Analise_de_CreditoLayout);
        Painel_Gerenciar_Analise_de_CreditoLayout.setHorizontalGroup(
            Painel_Gerenciar_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Gerenciar_Analise_de_CreditoLayout.createSequentialGroup()
                .addComponent(Painel_Analise_de_Credito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Painel_Gerenciar_Analise_de_CreditoLayout.setVerticalGroup(
            Painel_Gerenciar_Analise_de_CreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Gerenciar_Analise_de_CreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_Analise_de_Credito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel_Gerenciar_Analise_de_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel_Gerenciar_Analise_de_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAprovarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiGerenciar_Análise_de_Crédito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiGerenciar_Análise_de_Crédito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiGerenciar_Análise_de_Crédito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiGerenciar_Análise_de_Crédito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiGerenciar_Análise_de_Crédito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo_Pesquisa;
    private javax.swing.JPanel Painel_Analise_de_Credito;
    private javax.swing.JPanel Painel_Complemento_da_Pesquisa;
    private javax.swing.JPanel Painel_Gerenciar_Analise_de_Credito;
    private javax.swing.JPanel Painel_Pedido;
    private javax.swing.JPanel Painel_Período_da_Pesquisa;
    private javax.swing.JPanel Painel_Pesquisa;
    private javax.swing.JScrollPane Pedido;
    private javax.swing.JButton btnAprovar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnReprovar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxFiltro;
    private javax.swing.JFormattedTextField ftxtData_Final;
    private javax.swing.JFormattedTextField ftxtData_Inicial;
    private javax.swing.JLabel lblData_Final;
    private javax.swing.JLabel lblData_Inicial;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JRadioButton rbtnCodigo_do_Cliente;
    private javax.swing.JRadioButton rbtnNumero_da_Compra;
    private javax.swing.JRadioButton rbtnTodos;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTextField txtCodigo_Cliente;
    private javax.swing.JTextField txtNumero_Compra;
    // End of variables declaration//GEN-END:variables
}
